---
  - name: install unit file to systemd
    template:
      src: templates/node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode: 0600