---
  - name: download node exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v{{ version.node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
      dest: /opt