---
#  - name: find cert files
#    ansible.builtin.find:
#      paths: "{{ OLD_OS_PATH_CONFIG }}"
#      file_type: file
#      patterns: 
#        - "{{ CERT_NAME }}.*"
#      recurse: false
#    register: cert_files
#    when: CERT_NAME is defined

#  - name: set cert files list variable
#    ansible.builtin.set_fact:
#      cert_files_list: "{{ cert_files.files }}"
#    when: CERT_NAME is defined 

  - name: copy cert files
    ansible.builtin.copy:
      remote_src: true
      src: "{{ item }}"
      dest: "{{ OPENSEARCH_PATH_CONF }}"
    loop: "{{ cert_files.files | map(attribute='path') | list }}"
    when: cert_files_list is defined


