---
  - name: find pem files
    ansible.builtin.find:
      paths: "{{ OLD_OS_PATH_CONFIG }}"
      file_type: file
      patterns: "*.pem"
      recurse: false
    register: pem_files

  - name: set pem files list variable
    ansible.builtin.set_fact:
      pem_files_list: "{{ pem_files.files }}"

  - name: copy pem files
    ansible.builtin.copy:
      remote_src: true
      src: "{{ item }}"
      dest: "{{ OPENSEARCH_PATH_CONF }}"
    loop: "{{ pem_files.files | map(attribute='path') | list }}"


