---
  - name: copy other files
    ansible.builtin.copy:
      remote_src: true
      src:
        - "{{ OLD_OS_PATH_CONFIG }}/jvm.options"
        - "{{ OLD_OS_PATH_CONFIG }}/jvm.options.d"
        - "{{ OLD_OS_PATH_CONFIG }}/opensearch.keystore"
        - "{{ OLD_OS_PATH_CONFIG }}/*.pem"
      dest: "{{ OPENSEARCH_PATH_CONF }}"
      force: true
      mode: preserve
    register: copying

  - name: debug copying other files
    ansible.builtin.debug:
      var: copying