---
  - name: extract tarball file
    become: true
    ansible.builtin.unarchive:
      remote_src: true
      src: "{{ TARBALL_FILE_LOCATION }}"
      dest: /opt
  
  - name: find the new extracted directory
    ansible.builtin.find:
      paths: /opt
      file_type: directory
      patterns:
        - "*{{ NEW_OS_VERSION }}*"
    register: DIRNAME
  
  - name: debug new os path
    ansible.builtin.debug:
      var: DIRNAME['files'][0]['path']

  - ansible.builtin.set_fact:
      OPENSEARCH_PATH_CONF: "{{ DIRNAME['files'][0]['path'] }}/config"
  
  - name: debug config path
    ansible.builtin.debug:
      var: OPENSEARCH_PATH_CONF